# Generated by Django 6.0.3 on 2026-04-28 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gols_casa', models.IntegerField()),
                ('gols_fora', models.IntegerField()),
                ('data', models.DateField()),
                ('time_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casa', to='core.time')),
                ('time_fora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fora', to='core.time')),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('posicao', models.CharField(max_length=50)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.time')),
            ],
        ),
    ]
